site_name: backend
site_description: Professional Anonymous Network for Students
repo_url: https://github.com/rashadphil/vision-backend
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/rashadphil">rashadphil</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
